services:
  - type: web
    name: venture-ideation-tool
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false # This makes it a secret that needs to be entered manually
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render will automatically expose this port
    autoDeploy: true
    plan: free # Specifies the free tier